### PR TITLE
Adding a .gitignore to stop git from tracking different files

### PR DESCRIPTION
**Pull request by Hamath-Eltrael**
plugins, wrong and unnamed files, personal files and some systemfiles that I noticed on MacOS. see #9 for last try and **_info!_** 

If it throws another error it might get interesting. But currently it says it's mergeable without problems. **Do a recent backup**

### CODE REVIEW

**Comment by abdullahkhursheed22** [comment]
Okay, so it worked. Although I believe no files were deleted.

**Comment by Hamath-Eltrael** [comment]
Just to be sure, could you do the following commands in the main vault-directory? That should tell git to no longer track them. And then the .gitignore will keep git from tracking them again. You'd need to have git installed for that(but I'm guessing that you already have)

`git rm --cached .obsidian/*` <--- this one should not throw an error. Start with this one. If it does, get back to me. 
`git rm --cached 05*-*Personal/` <--- Just a precaution. If it throws an error, that'd be the best case. 
`git rm --cached .obsidian-git-data` <--- Just a precaution. If it throws an error, that's ok. 
`git rm --cached Untitled*` <--- Throws an error when there are no broken filenames files, which is likely. 
`git rm --cached null*` <--- Throws an error when there are no unnamed files, which is likely. 
`git rm --cached .trash/` <--- Throws an error on all non MacOS, and might even there.
`git rm --cached .DS_Store`  <--- Throws an error on all non MacOS, and might even there.
`git rm --cached resources/.DS_Store`  <--- Throws an error on all non MacOS, and might even there.

this should remove the files and together with the .gitignore will stop them from re-appearing.

**Comment by abdullahkhursheed22** [comment]
Hey, thanks for detailing the process!

I have attached the results of each command in the image below:

image

**Comment by Hamath-Eltrael** [comment]
That's looking perfect. Now we should be all set! Fingers crossed! This should update the repo with the next update from your end.

**Comment by abdullahkhursheed22** [comment]
Got it!

**Comment by Hamath-Eltrael** [comment]
Ok, It doesn't seem to have.. You might have to manually remove them from GitHub. Should be only `.obsidian` See https://github.blog/changelog/2021-01-11-delete-directory-from-the-web/#:~:text=Browse%20to%20the%20directory%20in,change%20using%20a%20pull%20request

**Comment by abdullahkhursheed22** [comment]
Okay, I'll delete it manually on GitHub. Do I only need to delete the .obsidian folder?

**Comment by Hamath-Eltrael** [comment]
yes, all others are just precautions as to not get them into the repository in the future. Only `.obisidian`

**Comment by abdullahkhursheed22** [comment]
Done.

**Comment by abdullahkhursheed22** [comment]
By the way, GitHub doesn't allow me to "push origin" because I deleted the .obsidian file.

image

**Comment by Hamath-Eltrael** [comment]
Hmmm, what are the option under „Resolve“? FYI I never used the GitHub interface for pushing. But I’ll try to figure it out. Am 17.07.2023 um 19:46 schrieb Abdullah Khursheed ***@***.***>:﻿
By the way, GitHub doesn't allow me to "push origin" because I deleted the .obsidian file.

**Comment by abdullahkhursheed22** [comment]
I used the Obsidian Git plugin to push changes in Obsidian to GitHub. 

It may be giving an error because the plugin may need the .obsidian folder to work. In that case, I can try adding it back.

These are the options under Resolve:

image

**Comment by Hamath-Eltrael** [comment]
Did you pull before doing any changes? And then re-add the now (hopefully) missing files from the backup?

**Comment by Hamath-Eltrael** [comment]
And yes, it should need the `.obsidian` folder. It's probably saved in there after all. But it should only be needed on the local drive you're using and not on GitHub.

**Comment by abdullahkhursheed22** [comment]
> But it should only be needed on the local drive you're using and not on GitHub.

I readded the missing files in .obsidian from the backup and now it seems to be working. But now .obsidian is back on GitHub too. Should I try deleting it again?

**Comment by Hamath-Eltrael** [comment]
-.- now I'm starting to get annoyed with this issue, not with any person - just the problem!

You have pulled the Repo down to your local files, yes? you can make sure of that by looking for the .gitignore file in your main Vault folder.

**Comment by Hamath-Eltrael** [comment]
Oh and look at its contents! It should be the same as on Github!

**Comment by abdullahkhursheed22** [comment]
> You have pulled the Repo down to your local files, yes?

Um, I push the changes to GitHub using Obsidian Git whenever I make a change in Obsidian.

> you can make sure of that by looking for the .gitignore file in your main Vault folder.

The content of the local .gitignore files is the same as that of the one on GitHub.

Maybe we can skip this issue if it's not working. :/

**Pull request merged**
